import java.io.File;
import java.util.Calendar;

import org.apache.log4j.Logger;


/**
 * @author ergindoganyildiz
 * 
 * Dec 16, 2015
 */
public class Generator {
	
//	private static String long_passage = "BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM."
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM"
//			+ " BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM";
	
//	private static String short_passage = "BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM. BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM."
//			+ " BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM. BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM."
//			+ " BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM. BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM."
//			+ " BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM. BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM."
//			+ " BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM. BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM.";
//
//	private static String long_passage = "BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM. BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM."
//			+ " BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM. BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM."
//			+ " BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM. BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM."
//			+ " BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM. BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM."
//			+ " BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM. BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM.";
	
	private static String short_passage = "BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM. BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM."
			+ "BEN OKULA GITTIM GITTIM, SONRA GERI GELDIM VE OTURDUM.";
	
	private static String long_passage = "BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM."
			+ "BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM. BEN KITAP OKUDUM SONRA TEKRAR OKUDUM OKUDUM OKUDUM.";
	
	private static String yazar1 = "Hakan Kahraman";
	private static String yazar2 = "Ferhan Duman";
	
	private static final Logger logger = Logger.getLogger(Generator.class);
	
	public static void main(String args[]){
		
		OutputController.configureLogger(new File("/Users/ergindoganyildiz/Desktop/Loadtest/PENGUENCrawler.txt"), false);
		
		int yazar1PassageCount = 10;
		
		int yazar2PassageCount = 10;
		
		
		for(int i = 0; i < yazar1PassageCount; i++){
			String myPassage = long_passage;
			for(int j = 0; j < i; j++){
				myPassage += " " + "EKLEME.";
			}
			KoseYazisi koseYazisi = new KoseYazisi(yazar1, "Baslik " + i, Calendar.getInstance().getTime(), myPassage);
			String oneRecord = Utils.getOneRecord(koseYazisi);
			logger.warn(oneRecord);
			logger.warn("------------------------------------------------------------------------------------------ \n");
		}
		
		OutputController.configureLogger(new File("/Users/ergindoganyildiz/Desktop/Loadtest/LOMBAKCrawler.txt"), false);
		
		for(int j = 0; j < yazar2PassageCount; j++){
			String myPassage = short_passage;
			for(int y = 0; y < j; y++){
				myPassage += " " + "EKLEME.";
			}
			
			KoseYazisi koseYazisi = new KoseYazisi(yazar2, "Baslik " + j, Calendar.getInstance().getTime(), myPassage);
			String oneRecord = Utils.getOneRecord(koseYazisi);
			logger.warn(oneRecord);
			logger.warn("------------------------------------------------------------------------------------------ \n");
		}
		
	}

}
